"""Added ingredients and instructions to schema

Revision ID: 934271cffeae
Revises: e622e91a9d6a
Create Date: 2023-05-28 15:21:36.388408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934271cffeae'
down_revision = 'e622e91a9d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
